CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username VARCHAR(40) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(40) NOT NULL,
  registration_date TIMESTAMP WITH TIME ZONE NOT NULL
);
        
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  author_id BIGINT NOT NULL REFERENCES users(id),
  description TEXT,
  post_date TIMESTAMP WITH TIME ZONE NOT NULL
);
        
CREATE TABLE IF NOT EXISTS image_storage (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  original_name VARCHAR(255),
  file_path VARCHAR(1024),
  post_id BIGINT NOT NULL REFERENCES posts(id)
);